language: r
warnings_are_errors: false
sudo: required
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
